apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-repos
  namespace: &namespace flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: *namespace
  path: ./kubernetes/core/repos
  prune: true
  retryInterval: 2m
  # Flux repositories under this need flux-system hardcoded as namespace for Renovate lookups
  targetNamespace: *namespace
  wait: true
