# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: rustfs-secret
    creationPolicy: Owner
    template:
      data:
        RUSTFS_ACCESS_KEY: "{{ .RUSTFS_ROOT_USER }}"
        RUSTFS_SECRET_KEY: "{{ .RUSTFS_ROOT_PASSWORD }}"
        RUSTFS_RPC_SECRET: "{{ .RUSTFS_RPC_SECRET }}"
        RUSTFS_IDENTITY_OPENID_CLIENT_SECRET: "{{ .RUSTFS_OIDC_CLIENT_SECRET }}"
  data:
    - secretKey: RUSTFS_ROOT_USER
      remoteRef:
        key: RUSTFS_ROOT_USER
    - secretKey: RUSTFS_ROOT_PASSWORD
      remoteRef:
        key: RUSTFS_ROOT_PASSWORD
    - secretKey: RUSTFS_RPC_SECRET
      remoteRef:
        key: RUSTFS_RPC_SECRET
    - secretKey: RUSTFS_OIDC_CLIENT_SECRET
      remoteRef:
        key: RUSTFS_OIDC_CLIENT_SECRET
