apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 41.2.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    deployment:
      enabled: true
      replicas: 2
    tlsStore:
      default:
        defaultCertificate:
          secretName: "${DOMAIN/./-}-tls"
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: false
    rbac:
      enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: false
    providers:
      kubernetesCRD:
        enabled: true
        allowExternalNameServices: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
      kubernetesGateway:
        enabled: true
        # This option currently enables support for TCPRoute and TLSRoute.
        experimentalChannel: true
    gateway:
      name: traefik-public
      annotations:
        external-dns.alpha.kubernetes.io/target: &hostname "tun-${CLUSTER_NAME}.${DOMAIN}"
      infrastructure:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: *hostname
      listeners:
        web:
          port: 80
          protocol: HTTP
          namespacePolicy:
            from: All
        websecure:
          port: 443
          protocol: HTTPS
          namespacePolicy:
            from: All
          certificateRefs:
            - kind: Secret
              name: "${DOMAIN/./-}-tls"
    additionalArguments:
      - "--api.insecure=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
      - "--providers.kubernetesingress.ingressendpoint.ip=${LB_INT_IP}"
      - "--providers.kubernetescrd.allowexternalnameservices=true"
    ports:
      web:
        port: 80
      websecure:
        port: 443
        exposedPort: 443
        http:
          tls:
            enabled: true
            options: "default"
        http3:
          enabled: true
    service:
      type: LoadBalancer
      annotations:
        metallb.io/loadBalancerIPs: ${LB_INT_IP}
      spec:
        externalTrafficPolicy: Cluster
    log:
      level: "INFO"
    accessLog:
      enabled: true
