[plugins]
fnox-env = "https://github.com/jdx/mise-env-fnox"

[tools]
age = "1.3.1"
k3sup = "0.13.12"
fnox = "1.20.0"

[env]
_.fnox-env = { tools = true }
TF_VAR_cluster_env = "lab"
TF_VAR_cluster_name = "sed-k8s-01"
TF_VAR_cluster_region = "au"
TF_VAR_node1_mac_addr = { value = "{{ env.NODE1_MAC_ADDR }}", tools = true }
TF_VAR_node1_hostname = { value = "{{ env.NODE1_HOSTNAME }}", tools = true }
TF_VAR_cluster_token = { value = "{{ env.CLUSTER_TOKEN }}", tools = true }
TF_VAR_matchbox_url = { value = "{{ env.MATCHBOX_URL }}", tools = true }
