# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: omlx
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: omlx-secret
    creationPolicy: Owner
    template:
      data:
        Authorization: "Bearer {{ .OMLX_KEY }}"
  data:
    - secretKey: OMLX_KEY
      remoteRef:
        key: OMLX_KEY
