# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-memini
  namespace: postgres
spec:
  name: memini
  owner: memini
  cluster:
    name: postgres
  extensions:
    - name: vector
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: postgres-memini
spec:
  cluster:
    name: postgres
  databaseRoleReclaimPolicy: retain
  ensure: present
  login: true
  name: memini
  superuser: false
  passwordSecret:
    name: memini-postgres
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memini-postgres
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: memini-postgres
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: kubernetes.io/basic-auth
      data:
        username: "memini"
        password: "{{ .MEMINI_PG_PASSWORD }}"
  data:
    - secretKey: MEMINI_PG_PASSWORD
      remoteRef:
        key: MEMINI_PG_PASSWORD
