apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
type: Opaque
stringData:
  CF_TUNNEL_ID: ${CF_TUNNEL_ID}
  DEX_GITHUB_CLIENT_ID: ${DEX_GITHUB_CLIENT_ID}
  DEX_GITHUB_CLIENT_SECRET: ${DEX_GITHUB_CLIENT_SECRET}
  HERMES_DASHBOARD_CLIENT_SECRET: ${HERMES_DASHBOARD_CLIENT_SECRET}
  RUSTFS_OIDC_CLIENT_SECRET: ${RUSTFS_OIDC_CLIENT_SECRET}
  OPEN_KNOWLEDGE_OIDC_CLIENT_SECRET: ${OPEN_KNOWLEDGE_OIDC_CLIENT_SECRET}
