# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: dex-secret
    template:
      data:
        DEX_GITHUB_CLIENT_ID: "{{ .DEX_GITHUB_CLIENT_ID }}"
        DEX_GITHUB_CLIENT_SECRET: "{{ .DEX_GITHUB_CLIENT_SECRET }}"
        DEX_GOOGLE_CLIENT_ID: "{{ .DEX_GOOGLE_CLIENT_ID }}"
        DEX_GOOGLE_CLIENT_SECRET: "{{ .DEX_GOOGLE_CLIENT_SECRET }}"
        DEX_GOOGLE_HOSTED_DOMAIN: "{{ .DEX_GOOGLE_HOSTED_DOMAIN }}"
        HERMES_DASHBOARD_CLIENT_SECRET: "{{ .HERMES_DASHBOARD_CLIENT_SECRET }}"
        RUSTFS_OIDC_CLIENT_SECRET: "{{ .RUSTFS_OIDC_CLIENT_SECRET }}"
  data:
    - secretKey: HERMES_DASHBOARD_CLIENT_SECRET
      remoteRef:
        key: HERMES_DASHBOARD_CLIENT_SECRET
    - secretKey: RUSTFS_OIDC_CLIENT_SECRET
      remoteRef:
        key: RUSTFS_OIDC_CLIENT_SECRET
    - secretKey: DEX_GITHUB_CLIENT_ID
      remoteRef:
        key: DEX_GITHUB_CLIENT_ID
    - secretKey: DEX_GITHUB_CLIENT_SECRET
      remoteRef:
        key: DEX_GITHUB_CLIENT_SECRET
    - secretKey: DEX_GOOGLE_CLIENT_ID
      remoteRef:
        key: DEX_GOOGLE_CLIENT_ID
    - secretKey: DEX_GOOGLE_CLIENT_SECRET
      remoteRef:
        key: DEX_GOOGLE_CLIENT_SECRET
    - secretKey: DEX_GOOGLE_HOSTED_DOMAIN
      remoteRef:
        key: DEX_GOOGLE_HOSTED_DOMAIN
