apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayParameters
metadata:
  name: agentgateway-config
  namespace: agentgateway-system
spec:
  service:
    metadata:
      annotations:
        metallb.io/loadBalancerIPs: ${AG_INT_IP}
