apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agentgateway
spec:
  dependsOn:
    - name: agentgateway-crds
  interval: 5m
  releaseName: agentgateway
  chartRef:
    kind: OCIRepository
    name: agentgateway
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    controller:
      image:
        pullPolicy: Always
