apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: high-availability
spec:
  addresses:
    - ${BGP_CIDR}
  autoAssign: false
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: high-availability
spec:
  myASN: 64513
  peerASN: 64512
  peerAddress: ${BGP_PEER_ADDR}
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: high-availability
spec:
  ipAddressPools:
    - high-availability
  peers:
    - high-availability
