# yaml-language-server: $schema=https://schemas.budimanjojo.com/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-sdk-server-secret
            namespace: external-secrets
      caProvider:
        name: bitwarden-sdk-server-cert
        type: Secret
        namespace: external-secrets
        key: ca.crt
      organizationID: "${BW_ORGANIZATION_ID}"
      projectID: "${BW_PROJECT_ID}"
