# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: github-webhook-token-secret
    template:
      data:
        token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: FLUX_GITHUB_WEBHOOK_TOKEN
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: flux-system
    template:
      data:
        githubAppID: "{{ .githubAppID }}"
        githubAppInstallationOwner: "{{ .githubAppInstallationOwner }}"
        githubAppPrivateKey: "{{ .githubAppPrivateKey }}"
  data:
    - secretKey: githubAppID
      remoteRef:
        key: FLUX_GH_APP_ID
    - secretKey: githubAppInstallationOwner
      remoteRef:
        key: FLUX_GH_APP_PRIVATE_KEY
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: FLUX_GH_APP_PRIVATE_KEY
