apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agentgateway-crds
spec:
  interval: 5m
  releaseName: agentgateway-crds
  chartRef:
    kind: OCIRepository
    name: agentgateway-crds
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
