# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: tun.${CLUSTER_NAME}.${DOMAIN}
      recordType: CNAME
      targets:
        - ${CF_TUNNEL_ID}.cfargotunnel.com
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: internal-lb
spec:
  endpoints:
    - dnsName: int.${CLUSTER_NAME}.${DOMAIN}
      recordType: A
      targets:
        - ${LB_INT_IP}
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
