# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: cloudflare-tunnel-secret
    template:
      data:
        TUNNEL_TOKEN: |-
          {{ toJson (dict "a" .CF_ACCOUNT_TAG "t" .CF_TUNNEL_ID "s" .CF_TUNNEL_SECRET) | b64enc }}
  data:
    - secretKey: CF_ACCOUNT_TAG
      remoteRef:
        key: CF_ACCOUNT_TAG
    - secretKey: CF_TUNNEL_ID
      remoteRef:
        key: CF_TUNNEL_ID
    - secretKey: CF_TUNNEL_SECRET
      remoteRef:
        key: CF_TUNNEL_SECRET
