multitenancy:
  enabled: false
commonAnnotations:
  cluster-region: ${CLUSTER_REGION}
  cluster-env: ${CLUSTER_ENV}
serviceMonitor:
  create: false
web:
  config:
    authentication:
      type: Anonymous
      anonymous:
        username: flux
        groups:
          - flux-web-admin
  networkPolicy:
    create: false
