multitenancy:
  enabled: false
commonAnnotations:
  cluster-region: ${CLUSTER_REGION}
  cluster-env: ${CLUSTER_ENV}
  reloader.stakater.com/auto: "true"
serviceMonitor:
  create: false
web:
  config:
    baseURL: https://flux.int.${REGION}.${ENVIRONMENT}.${DOMAIN}
    authentication:
      type: Anonymous
      anonymous:
        username: flux
        groups:
          - flux-web-admin
  networkPolicy:
    create: false
