# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: hermes-secret
    template:
      data:
        HERMES_API_KEY: "{{ .HERMES_API_KEY }}"
        GITHUB_PERSONAL_ACCESS_TOKEN: "{{ .GITHUB_TOKEN }}"
  data:
    - secretKey: HERMES_API_KEY
      remoteRef:
        key: HERMES_API_KEY
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: GITHUB_TOKEN
