apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: cloudflare-secret
    template:
      data:
        CF_API_TOKEN: "{{ .key }}"
  data:
    - secretKey: key
      remoteRef:
        key: cf_api_token
