# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./sshkey.yaml
  - ./pvc.yaml
  - ./helmrelease.yaml
  - ./mcp.yaml
configMapGenerator:
  - name: open-knowledge-configmap
    files:
      - install.sh=./resources/install.sh
      - start.sh=./resources/start.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
