apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
data:
  CLUSTER_REGION: ${CLUSTER_REGION}
  CLUSTER_ENV: ${CLUSTER_ENV}
  CLUSTER_NAME: ${CLUSTER_NAME}
  ENVIRONMENT: ${ENVIRONMENT}
  DATACENTER: ${DATACENTER}
  DOMAIN: ${DOMAIN}
  LB_INT_IP: ${LB_INT_IP}
  BGP_CIDR: ${BGP_CIDR}
  ACME_EMAIL: ${ACME_EMAIL}
