[tools]
aube = "1.41.0"
fd = "10.4.2"
gh = "2.98.0"
hk = "1.56.1"
jq = "1.8.2"
rg = "15.2.0"
"github:bdellegrazie/git-credential-github-app" = "0.4.5"
rust = "latest"

[tools."cargo:https://github.com/block/buzz"]
version = "tag:desktop-v0.5.17"
crate = "buzz-cli"
