# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./app-template.yaml
  - ./bitwarden-sdk-server.yaml
  - ./cert-manager.yaml
  - ./cnpg.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./metallb.yaml
  - ./node-feature-discovery-charts.yaml
  - ./prometheus.yaml
  - ./toolhive.yaml
  - ./traefik.yaml
  - ./trust-manager.yaml
  - ./weave.yaml
