# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: pocket-id-secret
    creationPolicy: Owner
    template:
      data:
        DB_CONNECTION_STRING: "postgresql://pocket-id:{{ .POCKET_ID_PG_PASSWORD }}@postgres-rw.database.svc/pocket-id?sslmode=disable"
        ENCRYPTION_KEY: "{{ .POCKET_ID_ENCRYPTION_KEY }}"
  data:
    - secretKey: POCKET_ID_PG_PASSWORD
      remoteRef:
        key: POCKET_ID_PG_PASSWORD
    - secretKey: POCKET_ID_ENCRYPTION_KEY
      remoteRef:
        key: POCKET_ID_ENCRYPTION_KEY
